export const SET_SERVERERROR = "SET_SERVERERROR"


export const SET_USER = "SET_USER"


export const SET_NEWUSER = "SET_NEWUSER"


export const CLEAR_USER = "CLEAR_USER"


export const PROJECTS_INIT = "PROJECTS_INIT"


export const SET_PUBLISHEDPROJECT = "SET_PUBLISHEDPROJECT"


export const SET_DRAFTEDPROJECT = "SET_DRAFTEDPROJECT"


export const SET_REVIEWPROJECT = "SET_REVIEWPROJECT"


export const PROJECTS_LOADED = "PROJECTS_LOADED"


export const UPDATE_PROJECT = "UPDATE_PROJECT"


export const DELETE_PROJECT = "DELETE_PROJECT"


export const DISABLER_ON = "DISABLER_ON"


export const DISABLER_OFF = "DISABLER_OFF"


export const SET_GLINTHUBSPACEPROJECT = "SET_GLINTHUBSPACEPROJECT"


export const GLINTHUBSPACEPROJECTS_LOADED = "GLINTHUBSPACEPROJECTS_LOADED"


export const GLINTHUBSPACEFILTER_TEXT = "GLINTHUBSPACEFILTER_TEXT"


export const GLINTHUBSPACEFILTER_TECH = "GLINTHUBSPACEFILTER_TECH"
